### PR TITLE
gh-pages added with the url of original repo in homepage tag in packa…

### PR DESCRIPTION
**Pull request by hurali97**
…ge.json

Hi ! Please merge this and gh-pages-added branch and use the terminal in the project directory to execute :
npm run deploy

let me know if it is successfully deployed and accessible at : 
https://gaurav-gogia.github.io/pakdemon/

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
Sure, will try this now :)

**Comment by gaurav-gogia** [comment]
Well, its not working for me. 

Error:
`28 error Failed at the pakdemon@0.1.0 deploy script.`

Not sure what's going wrong here.

PS: I'm building this in docker

**Comment by hurali97** [comment]
Hi ! I have done this before with my projects, If you feel safe , you can
make me work on master, however it won't affect your code.

**Comment by gaurav-gogia** [comment]
Yea, that's fine. But could you please explain what's causing this error? I've been out of touch with JS and web development in general since over a year so that would be helpful :)

**Comment by hurali97** [comment]
I am having trouble finding out the issue because the forked repo doesn't
throw any error. Can I directly try to deploy the original repo ? It won't
affect any code though.

**Comment by gaurav-gogia** [comment]
Hey, sorry for late response. 

Yea, sure deploy on master and test. Let me know if it works for you :)

**Comment by hurali97** [comment]
Hi ! I overcame the previous error which you were facing buy I can't deploy
it as I am not in the maintainer of the repo, so it gives me this error. If
you can add me in the maintainers of the repo or give me the permissions to
write , I hope I will get this done.

**Comment by gaurav-gogia** [comment]
Sure I could add you as a maintainer :)

Also, could you explain what that error was all about? Why was it happening and how did you manage to solve it?

**Comment by hurali97** [comment]
It was the babel runtime version issue, it was coming out of material-ui.
So, I google alot and somewhere someone said to install the same exact
version. So, it worked that way .

On 13-Oct-2019 11:41 PM, "Gaurav Gogia" <notifications@github.com> wrote:

Sure I could add you as a maintainer :)

Also, could you explain what that error was all about? Why was it happening
and how did you manage to solve it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gaurav-gogia/pakdemon/pull/51?email_source=notifications&email_token=ALJEVTTX5TODQUP3ZBV2HRTQONTWPA5CNFSM4I7PL25KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBC43TA#issuecomment-541445580>,
or unsubscribe

**Comment by gaurav-gogia** [comment]
I see. Thanks you for the support ^.^

**Comment by hurali97** [comment]
Hi ! Can you please now check by hitting this in terminal,
Npm run deploy

**Comment by gaurav-gogia** [comment]
Sure, will try this now :)

**Comment by gaurav-gogia** [comment]
I keep getting error in events.js :/

Steps to reproduce:

1. `npm install`
2. `npm audit fix`
3. `npm run deploy`

**Pull request merged**
